services:
  lstar-rocq:
    build:
      context: ./containers/lstar-rocq
      args:
        TARGET: gnutls-3-3-8
  gnutls-3-3-8:
    build:
      context: ./containers/gnutls
      args:
        VERSION: "3_3_8"
  gnutls-3-3-12:
    build:
      context: ./containers/gnutls
      args:
        VERSION: "3_3_12"
  statelearner:
    build:
      context: ./containers/statelearner
      args:
        TARGET: gnutls-3-3-8
