(executables
 (names alternating mod3 div7 alternating_socket traffic vending suffix tls)
 (public_names
  dfa.alternating
  dfa.mod3
  dfa.div7
  dfa.alternating_socket
  moore.traffic
  mealy.vending
  nfa.suffix
  mealy.tls)
 (libraries lstar unix threads str)
 (flags
  (:standard -w -26))
 (package lstar))
